!include <C4/C4_Container>

!$EXTERNAL_SYSTEM_COLOR = "#555555"
!$SYSTEM_COLOR = "#1168bd"
!$CONTAINER_COLOR = "#438dd5"
!$PERSON_COLOR = "#09427b"
 
!$NEW_RESOURCE_COLOR = "#0044A3"
!$UNCHANGED_COLOR = "#AAAAAA"
!$CHANGED_COLOR = "#347DE3"

UpdateElementStyle("external_system", $bgColor=$EXTERNAL_SYSTEM_COLOR, $borderColor=$EXTERNAL_SYSTEM_COLOR, $fontColor=white, $legendText="External System")
UpdateElementStyle("system", $bgColor=$SYSTEM_COLOR, $borderColor=$SYSTEM_COLOR, $fontColor=white, $legendText="System")
UpdateElementStyle("container", $bgColor=$CONTAINER_COLOR, $borderColor=$CONTAINER_COLOR, $fontColor=white, $legendText="Container")
UpdateElementStyle("boundary", $legendText="Boundary (dashed)")
UpdateElementStyle("person", $bgColor=$PERSON_COLOR, $borderColor=$PERSON_COLOR, $fontColor=white, $legendText="External System", $legendText="Person")
 
AddContainerTag("new_resource", $bgColor=$NEW_RESOURCE_COLOR, $fontColor=white, $legendText="New Resource")
AddContainerTag("unchanged", $bgColor=$UNCHANGED_COLOR, $borderColor=$UNCHANGED_COLOR, $fontColor=white, $legendText="Unchanged")
AddContainerTag("changed", $bgColor=$CHANGED_COLOR, $borderColor=$CHANGED_COLOR, $fontColor=white, $legendText="Changed")

SHOW_PERSON_OUTLINE()

skinparam lengthAdjust none
